spring:
  config:
    activate:
      on-profile: local
  jwt:
    secret: ed46b9093e4683f177ff14b160339832b2424f7722840e6321d609b2e30ae3ce496bf51e292b940cbd7869ee071f8c539c9e2b0e2f82200deb11c671e15ab2e3
  mvc:
    converters:
      preferred-json-mapper: gson

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/harpsharp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: wlghks24461!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show_sql: true
  logging.level:
    org.hibernate.SQL: debug

  cloud:
    aws:
      s3:
        bucket: harpimages
        stack.auto: false
      cdn:
        domain: d2165tdwy08x2f
