version: '3.8'

services:
  front:
    build: .
    networks:
      - harpsharp
    expose:
      - "3000"
    env_file:
      - ./.env.local  # 기본 환경 변수 파일
    volumes:
      - .:/app

networks:
  harpsharp:
    external: true

