services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    volumes:
      - ./:/tmp
    expose:
      - "8080"
    environment:
      - SWAGGER_JSON=/tmp/auth.json
    networks:
      - harpsharp

networks:
  harpsharp:
    external: true