services:
  auth:
    container_name: auth
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/harpsharp?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "wlghks24461!"
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - harpsharp

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger-auth
    volumes:
      - ./:/tmp
    ports:
      - "3000:8080"
    environment:
      - SWAGGER_JSON=/usr/share/nginx/html/authAPI.json
    networks:
      - harpsharp

networks:
  harpsharp:
    external: true
