version: "3"
services:
  board:
    container_name: board
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/harpsharp?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "wlghks24461!"
    networks:
      - harpsharp

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger-board
    volumes:
      - ./:/mnt
    expose:
      - "8080"
    environment:
      - SWAGGER_JSON=mnt/boardAPI.json
    networks:
      - harpsharp

networks:
  harpsharp:
    external: true
