version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy-nginx/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy-nginx.sh
      timeout: 60
      runas: ubuntu