services:
  todo:
    container_name: todo
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/harpsharp?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "wlghks24461!"
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - harpsharp
      - datasource

networks:
  harpsharp:
    external: true
  datasource:
    external: true